from enum import Enum

class ErrorTypes(Enum):
    ALREADY_EXISTS = "ALREADY_EXISTS"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR"
    FORBIDDEN_ERROR = "FORBIDDEN_ERROR"
    NOT_FOUND_ERROR = "NOT_FOUND_ERROR"
    SERVER_ERROR = "SERVER_ERROR"
    SMS_SENDING_FAILED = "SMS_SENDING_FAILED"
    MAIL_SENDING_FAILED = "MAIL_SENDING_FAILED"