services:
    jfca-app:
        build: .
        container_name: jfca-app
        restart: always
        depends_on:
            - jfca-mongodb
        ports:
            - "4000:4000"
        environment:
            - DATABASE_URL=mongodb://mongo:27017/mydatabase
        volumes:
            - .:/app

    jfca-mongodb:
        image: mongo:6
        container_name: jfca-mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27018:27017"
        volumes:
            - mongodb_data:/data/db

    jfca-mongoexpress:
        image: mongo-express:latest
        container_name: jfca-mongoexpress
        restart: always
        depends_on:
            - jfca-mongodb
        ports:
            - "8082:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_SERVER: jfca-mongodb

volumes:
    mongodb_data:
